### ISSUE TITLE
doc

### ISSUE THREAD

**Issue by wuxu509** [didi/KnowAgent#17]
文档部分还不完善，logi-agent部分架构设计能否补全

**Comment by zhangliangboy** [comment]
doc目录中有较多的设计描述，部分架构设计你重点向了解哪些点？

**Comment by huqidong** [comment]
请参考 -- https://github.com/didi/LogiAM/blob/master/doc/%E6%BB%B4%E6%BB%B4%E5%BC%80%E6%BA%90Logi-AM%20%E4%B8%80%E7%AB%99%E5%BC%8F%E6%97%A5%E5%BF%97%E9%87%87%E9%9B%86%E5%B9%B3%E5%8F%B0.md
如不够，logi-agent部分架构设计你想了解哪些部分呢？
