### ISSUE TITLE
环境配置

### ISSUE THREAD

**Issue by aLazyBear** [didi/KnowAgent#18]
为什么我按照文档中的步骤，没有生成效应的静态文件呢。新手求指教

**Comment by zhangliangboy** [comment]
最近正在准备1.0的正式Release包，之前在前后端的资源打包方面遇到了些问题，预期7月中旬正式发布，届时会解决这个问题，如果想第一时间体验，可以加mike_zhangliang的微信，我拉你进天使群，到时手第一时间通知你

**Comment by zhangliangboy** [comment]
1.0版本已经发布，可以下载体验最新成熟版本
