### ISSUE TITLE
项目是干嘛的

### ISSUE THREAD

**Issue by dzhyw** [didi/KnowAgent#19]
这个项目到底是干嘛的，是agent管理还是采集日志的。不知所云。

**Comment by zhangliangboy** [comment]
聚焦日志2Kafka采集端到端解决方案，在运维管理方面，聚焦可观察、可诊断、简单易用；在数据质量方面，关注采集的及时性、完整性，我们会在7月中旬正式对外发布，届时有全新完整的体验
