### ISSUE TITLE
前端页面中有写死的kafka服务器地址

### ISSUE THREAD

**Issue by chinarenliwei** [didi/KnowAgent#21]
know-agent\agent-manager\agent-manager-console\src\api\api.ts
中，24行：
getTopicsBrokerServers: getApi('/normal/receivers/topics?brokerServers=10.255.0.49:9092'), // 获取接收端对应kafka集群的所有topic列表

导致的后果是在创建修改采集任务的第四步，本应该下拉选择topic，无法选择，只能手动输入。

**Comment by huqidong** [comment]
感谢你宝贵的建议，这个问题我们前端同学正在修改，我们会在下一个版本中修复并发布
