### ISSUE TITLE
新增采集任务，采集文件后缀名匹配正则输入框无法删除

### ISSUE THREAD

**Issue by LQfly** [didi/KnowAgent#26]
新增采集任务，采集文件后缀名匹配正则输入框如果选择了正则表达式在删除后，会有一个删除图标无法删除。

**Comment by zhangliangboy** [comment]
能否提供截图

**Comment by zhangliangboy** [comment]
![日志切割规则，未匹配到原始日志](https://user-images.githubusercontent.com/5287750/202139203-5ea15769-132f-44f0-b2c8-d296330bc197.jpeg)

日志切片规则，探索之后，原始日志文件未显示，如果没有任何正则表达，有一个固定图标显示

**Comment by zhangliangboy** [comment]
安排修复此问题

**Comment by huqidong** [comment]
已修复.
