### ISSUE TITLE
接收端kafka 服务地址长度限制太小

### ISSUE THREAD

**Issue by LQfly** [didi/KnowAgent#28]

**Comment by zhangliangboy** [comment]
有没有截图？ 是前端限制还是后端限制？

**Comment by zhangliangboy** [comment]
![集群地址需要扩展32个字符限制](https://user-images.githubusercontent.com/5287750/202138929-da85aa79-2e02-4686-a494-70d6bf4fd38c.jpeg)

**Comment by zhangliangboy** [comment]
确认是问题，安排修复

**Comment by huqidong** [comment]
已 fix.
