### ISSUE TITLE
前端项目npm run build报错

### ISSUE THREAD

**Issue by liangleiA** [didi/KnowAgent#45]
使用npm run start正常运行，使用 npm run build构建报错。 
node 版本  v16.20.2
npm 版本   6.14.8

![image](https://github.com/didi/KnowAgent/assets/22088365/dbfcf290-c550-4001-9322-7b8fe39497cd)

**Comment by liangleiA** [comment]
在agent-manager-console路径下执行mvn install 仍然报错

**Comment by liangleiA** [comment]
固定版本

**Comment by zjy090** [comment]
<execution>
            <id>install node and npm</id>
            <goals>
              <goal>install-node-and-npm</goal>
            </goals>
            <configuration>
              <nodeVersion>v12.20.0</nodeVersion>
              <npmVersion>6.14.8</npmVersion>  这里不是固定版本了吗？  我也碰到这个问题了 请教下你是如何解决的呢？
